# https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md
lexik_jwt_authentication:
    private_key_path: '%kernel.root_dir%/../%env(JWT_PRIVATE_KEY_PATH)%'
    public_key_path:  '%kernel.root_dir%/../%env(JWT_PUBLIC_KEY_PATH)%'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'
    token_ttl:        '%env(JWT_TOKEN_TTL)%'
    user_identity_field: username

    # token encoding/decoding settings
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
        crypto_engine:  openssl
        signature_algorithm: RS384

    token_extractors:
        authorization_header:      # look for a token as Authorization Header
            enabled: true
            prefix:  ''
            name:    Authorization
        cookie:                    # check token in a cookie
            enabled: false
            name:    BEARER
        query_parameter:           # check token in query string parameter
            enabled: false
            name:    bearer
