# https://github.com/nelmio/NelmioCorsBundle
nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['POST','GET','DELETE','PUT','OPTIONS']
        expose_headers: []
        max_age: 3600
