snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
            logging: "%kernel.debug%"
            options:
               read_write_timeout: 0
